# Generated by Django 3.0.2 on 2020-01-17 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member')),
            ],
            options={
                'ordering': ('-writeDate',),
            },
        ),
        migrations.CreateModel(
            name='QnAComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writeDate', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Member')),
                ('qna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.QnA')),
            ],
            options={
                'ordering': ('-writeDate',),
            },
        ),
    ]
